-- =========================================================
-- V11: Reviews
--
-- All schema for the review feature in one file:
--   * the reviews table (one review per student/course)
--   * the rating-aggregation trigger that keeps courses.avg_rating
--     and courses.review_count in sync (denormalized counters that
--     the catalogue in V5 reads directly)
--   * sp_upsert_review -- the write path with enrollment validation
--   * review indexes
-- =========================================================

-- =========================================================
-- 1. Reviews table
-- =========================================================

CREATE TABLE public.reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT NOT NULL,
    course_id  BIGINT NOT NULL,
    rating     SMALLINT NOT NULL,
    comment    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_reviews
        PRIMARY KEY (id),

    CONSTRAINT uq_reviews_user_course
        UNIQUE (user_id, course_id),

    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reviews_course
        FOREIGN KEY (course_id)
        REFERENCES public.courses (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_reviews_rating
        CHECK (rating >= 1 AND rating <= 5)
);

CREATE TRIGGER trg_reviews_set_updated_at
BEFORE UPDATE ON public.reviews
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 2. Rating aggregation trigger
-- =========================================================

-- Keeps courses.avg_rating and courses.review_count current after any
-- insert, update or delete on reviews.
CREATE OR REPLACE FUNCTION public.fn_update_course_rating()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_course_id BIGINT;
BEGIN
    v_course_id := COALESCE(NEW.course_id, OLD.course_id);

    IF v_course_id IS NOT NULL THEN
        UPDATE public.courses
        SET avg_rating = (
                SELECT COALESCE(ROUND(AVG(rating), 2), 0.00)
                FROM public.reviews
                WHERE course_id = v_course_id
            ),
            review_count = (
                SELECT COUNT(*)
                FROM public.reviews
                WHERE course_id = v_course_id
            )
        WHERE id = v_course_id;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_update_course_rating ON public.reviews;
CREATE TRIGGER trg_update_course_rating
AFTER INSERT OR UPDATE OR DELETE ON public.reviews
FOR EACH ROW
EXECUTE FUNCTION public.fn_update_course_rating();


-- =========================================================
-- 3. Review write path
-- =========================================================

-- Inserts or updates the student's review for a published course they
-- are enrolled in. One review per student/course (upsert).
CREATE OR REPLACE FUNCTION public.sp_upsert_review(
    p_student_id BIGINT,
    p_course_id  BIGINT,
    p_rating     SMALLINT,
    p_comment    TEXT
)
RETURNS TABLE (
    review_id  BIGINT,
    user_id    BIGINT,
    course_id  BIGINT,
    rating     SMALLINT,
    comment    TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_course_status VARCHAR(20);
    v_enrolled      BOOLEAN;
BEGIN
    IF p_rating IS NULL OR p_rating < 1 OR p_rating > 5 THEN
        RAISE EXCEPTION 'LTR01: Rating must be between 1 and 5.'
            USING ERRCODE = 'LTR01';
    END IF;

    SELECT c.status
    INTO v_course_status
    FROM public.courses c
    WHERE c.id = p_course_id;

    IF v_course_status IS NULL THEN
        RAISE EXCEPTION 'LTC11: Course % does not exist.', p_course_id
            USING ERRCODE = 'LTC11';
    END IF;

    IF v_course_status <> 'PUBLISHED' THEN
        RAISE EXCEPTION 'LTR02: Only published courses can be reviewed.'
            USING ERRCODE = 'LTR02';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM public.enrollments
        WHERE user_id = p_student_id
          AND course_id = p_course_id
          AND status IN ('active', 'completed')
    )
    INTO v_enrolled;

    IF NOT v_enrolled THEN
        RAISE EXCEPTION 'LTR03: Enroll in the course before leaving a review.'
            USING ERRCODE = 'LTR03';
    END IF;

    INSERT INTO public.reviews (user_id, course_id, rating, comment)
    VALUES (p_student_id, p_course_id, p_rating, NULLIF(BTRIM(COALESCE(p_comment, '')), ''))
    ON CONFLICT (user_id, course_id) DO UPDATE
        SET rating = EXCLUDED.rating,
            comment = EXCLUDED.comment
    RETURNING
        public.reviews.id,
        public.reviews.user_id,
        public.reviews.course_id,
        public.reviews.rating,
        public.reviews.comment,
        public.reviews.created_at,
        public.reviews.updated_at
    INTO review_id, user_id, course_id, rating, comment, created_at, updated_at;

    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE IN ('LTC11', 'LTR01', 'LTR02', 'LTR03') THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_upsert_review unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while saving the review: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;


-- =========================================================
-- 4. Review indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_reviews_course_rating
    ON public.reviews (course_id, rating);

CREATE INDEX IF NOT EXISTS idx_reviews_user_course
    ON public.reviews (user_id, course_id);
