-- =========================================================
-- Roles
-- =========================================================

CREATE TABLE public.roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_roles
        PRIMARY KEY (id),

    CONSTRAINT uq_roles_name
        UNIQUE (name),

    CONSTRAINT chk_roles_name
        CHECK (name IN ('STUDENT', 'INSTRUCTOR', 'ADMIN'))
);


-- =========================================================
-- Users
-- =========================================================

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email public.citext NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users
        PRIMARY KEY (id),

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT chk_users_email_not_blank
        CHECK (btrim(email::text) <> ''),

    CONSTRAINT chk_users_password_hash_not_blank
        CHECK (btrim(password_hash) <> ''),

    CONSTRAINT chk_users_first_name_not_blank
        CHECK (btrim(first_name) <> ''),

    CONSTRAINT chk_users_last_name_not_blank
        CHECK (btrim(last_name) <> ''),

    CONSTRAINT chk_users_account_status
        CHECK (
            account_status IN (
                'ACTIVE',
                'SUSPENDED',
                'DISABLED'
            )
        )
);


-- =========================================================
-- User role assignments
-- =========================================================

CREATE TABLE public.user_roles (
    user_id BIGINT NOT NULL,
    role_id SMALLINT NOT NULL,
    granted_by BIGINT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES public.roles (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_user_roles_granted_by
        FOREIGN KEY (granted_by)
        REFERENCES public.users (id)
        ON DELETE SET NULL
);


-- =========================================================
-- Automatically maintain users.updated_at
-- =========================================================

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- Initial system roles
-- =========================================================

INSERT INTO public.roles (name, description)
VALUES
    ('STUDENT', 'Can enroll in courses and complete learning activities'),
    ('INSTRUCTOR', 'Can create and manage assigned course content'),
    ('ADMIN', 'Can manage users, roles and platform administration')
ON CONFLICT (name) DO NOTHING;