CREATE TABLE IF NOT EXISTS public.instructor_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    request_message TEXT,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_instructor_requests
        PRIMARY KEY (id),

    CONSTRAINT fk_instructor_requests_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_instructor_requests_reviewed_by
        FOREIGN KEY (reviewed_by)
        REFERENCES public.users (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_instructor_requests_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX IF NOT EXISTS idx_instructor_requests_user_status
ON public.instructor_requests (user_id, status);

CREATE INDEX IF NOT EXISTS idx_instructor_requests_status_created
ON public.instructor_requests (status, created_at);