-- =========================================================
-- V6: Fix identity sequences after explicit-ID seed data
--
-- V3 inserted seed rows (users, courses, tracks) with explicit
-- id values. With GENERATED BY DEFAULT AS IDENTITY, PostgreSQL
-- does NOT advance the underlying sequence for explicit IDs.
-- The next auto-generated row would therefore collide with an
-- existing primary key (register / course-create / track-create
-- would fail with "duplicate key value violates unique
-- constraint"). This additive, idempotent migration re-aligns
-- each sequence to MAX(id) so the next value is MAX(id)+1.
-- No data is modified and no tables are rewritten.
-- =========================================================

SELECT setval(
    pg_get_serial_sequence('public.users', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.users)
);

SELECT setval(
    pg_get_serial_sequence('public.courses', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.courses)
);

SELECT setval(
    pg_get_serial_sequence('public.tracks', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.tracks)
);
