-- =========================================================
-- V7: Public Course Catalogue
--
-- Adds the database objects required for:
--   1. Active course categories
--   2. Published course catalogue
--   3. Course difficulty
--   4. Course slugs
--   5. Course-card descriptions and thumbnails
--   6. PostgreSQL full-text search
--   7. Category and difficulty filtering
--   8. Sorting and pagination
--
-- The existing courses table was created by V3.
-- Therefore, this migration extends that table instead of
-- creating it again.
-- =========================================================


-- =========================================================
-- 1. Categories
-- =========================================================

CREATE TABLE public.categories (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categories_name
        UNIQUE (name)
);


-- =========================================================
-- 2. Extend the existing courses table
-- =========================================================

ALTER TABLE public.courses
    ADD COLUMN category_id       BIGINT,
    ADD COLUMN slug              VARCHAR(255),
    ADD COLUMN short_description VARCHAR(500),
    ADD COLUMN thumbnail_url     TEXT,
    ADD COLUMN difficulty        VARCHAR(20) NOT NULL DEFAULT 'BEGINNER',
    ADD COLUMN avg_rating        NUMERIC(3,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN review_count      INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN published_at      TIMESTAMPTZ,
    ADD COLUMN search_vector     TSVECTOR;


-- =========================================================
-- 3. Add category relationship
-- =========================================================

ALTER TABLE public.courses
    ADD CONSTRAINT fk_courses_category
        FOREIGN KEY (category_id)
        REFERENCES public.categories (id)
        ON DELETE SET NULL;


-- =========================================================
-- 4. Populate catalogue fields for existing courses
-- =========================================================

UPDATE public.courses
SET
    slug =
        LEFT(
            COALESCE(
                NULLIF(
                    TRIM(
                        BOTH '-' FROM
                        REGEXP_REPLACE(
                            LOWER(title),
                            '[^a-z0-9]+',
                            '-',
                            'g'
                        )
                    ),
                    ''
                ),
                'course'
            ),
            220
        )
        || '-' || id::TEXT,

    short_description =
        CASE
            WHEN short_description IS NULL
                THEN LEFT(description, 500)
            ELSE short_description
        END,

    published_at =
        CASE
            WHEN status = 'PUBLISHED'
                THEN COALESCE(published_at, updated_at, created_at)
            ELSE published_at
        END,

    search_vector =
        SETWEIGHT(
            TO_TSVECTOR('english', COALESCE(title, '')),
            'A'
        )
        ||
        SETWEIGHT(
            TO_TSVECTOR('english', COALESCE(short_description, '')),
            'B'
        )
        ||
        SETWEIGHT(
            TO_TSVECTOR('english', COALESCE(description, '')),
            'C'
        )
        ||
        SETWEIGHT(
            TO_TSVECTOR('english', COALESCE(difficulty, '')),
            'D'
        );


-- Slug and search vector will always be generated by the trigger below.

ALTER TABLE public.courses
    ALTER COLUMN slug SET NOT NULL,
    ALTER COLUMN search_vector SET NOT NULL;


-- =========================================================
-- 5. Validation constraints
-- =========================================================

ALTER TABLE public.courses
    ADD CONSTRAINT chk_courses_difficulty
        CHECK (
            difficulty IN (
                'BEGINNER',
                'INTERMEDIATE',
                'ADVANCED'
            )
        ),

    ADD CONSTRAINT chk_courses_avg_rating
        CHECK (
            avg_rating >= 0.00
            AND avg_rating <= 5.00
        ),

    ADD CONSTRAINT chk_courses_review_count
        CHECK (
            review_count >= 0
        );


-- =========================================================
-- 6. Unique course slug
-- =========================================================

ALTER TABLE public.courses
    ADD CONSTRAINT uq_courses_slug
        UNIQUE (slug);


-- =========================================================
-- 7. Trigger function for catalogue fields
-- =========================================================

CREATE OR REPLACE FUNCTION public.fn_refresh_course_catalogue_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_slug TEXT;
BEGIN
    -- Difficulty values are stored consistently in uppercase.
    NEW.difficulty :=
        UPPER(
            COALESCE(
                NULLIF(BTRIM(NEW.difficulty), ''),
                'BEGINNER'
            )
        );

    -- Generate a slug automatically when one was not provided.
    IF NEW.slug IS NULL OR BTRIM(NEW.slug) = '' THEN

        v_slug :=
            TRIM(
                BOTH '-' FROM
                REGEXP_REPLACE(
                    LOWER(NEW.title),
                    '[^a-z0-9]+',
                    '-',
                    'g'
                )
            );

        IF v_slug IS NULL OR v_slug = '' THEN
            v_slug := 'course';
        END IF;

        NEW.slug :=
            LEFT(v_slug, 220)
            || '-'
            || NEW.id::TEXT;

    ELSE

        -- Normalize a manually provided slug.
        v_slug :=
            TRIM(
                BOTH '-' FROM
                REGEXP_REPLACE(
                    LOWER(BTRIM(NEW.slug)),
                    '[^a-z0-9]+',
                    '-',
                    'g'
                )
            );

        IF v_slug IS NULL OR v_slug = '' THEN
            v_slug := 'course-' || NEW.id::TEXT;
        END IF;

        NEW.slug := LEFT(v_slug, 255);

    END IF;

    -- Automatically record the first publication time.
  IF TG_OP = 'INSERT'
   AND NEW.status = 'PUBLISHED'
THEN
    NEW.published_at :=
        COALESCE(
            NEW.published_at,
            CURRENT_TIMESTAMP
        );

ELSIF TG_OP = 'UPDATE'
      AND NEW.status = 'PUBLISHED'
      AND OLD.status IS DISTINCT FROM 'PUBLISHED'
THEN
    NEW.published_at :=
        COALESCE(
            NEW.published_at,
            CURRENT_TIMESTAMP
        );
END IF;

    -- Keep the update timestamp current.
    IF TG_OP = 'UPDATE' THEN
        NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;

    -- Build the weighted full-text search vector.
    NEW.search_vector :=
        SETWEIGHT(
            TO_TSVECTOR(
                'english',
                COALESCE(NEW.title, '')
            ),
            'A'
        )
        ||
        SETWEIGHT(
            TO_TSVECTOR(
                'english',
                COALESCE(NEW.short_description, '')
            ),
            'B'
        )
        ||
        SETWEIGHT(
            TO_TSVECTOR(
                'english',
                COALESCE(NEW.description, '')
            ),
            'C'
        )
        ||
        SETWEIGHT(
            TO_TSVECTOR(
                'english',
                COALESCE(NEW.difficulty, '')
            ),
            'D'
        );

    RETURN NEW;
END;
$$;


-- =========================================================
-- 8. Trigger
-- =========================================================

CREATE TRIGGER trg_refresh_course_catalogue_fields
BEFORE INSERT OR UPDATE OF
    title,
    slug,
    short_description,
    description,
    difficulty,
    status,
    published_at
ON public.courses
FOR EACH ROW
EXECUTE FUNCTION public.fn_refresh_course_catalogue_fields();


-- =========================================================
-- 9. Catalogue indexes
-- =========================================================

-- Fast PostgreSQL full-text search.
CREATE INDEX idx_courses_search_vector
    ON public.courses
    USING GIN (search_vector);


-- Fast filtering of published courses.
CREATE INDEX idx_courses_public_catalogue
    ON public.courses (
        status,
        category_id,
        difficulty,
        published_at DESC
    );


-- Fast sorting by rating.
CREATE INDEX idx_courses_rating
    ON public.courses (
        avg_rating DESC,
        review_count DESC
    );


-- Fast loading of active categories.
CREATE INDEX idx_categories_active_name
    ON public.categories (
        is_active,
        name
    );


-- =========================================================
-- 10. Public course catalogue search function
-- =========================================================

CREATE OR REPLACE FUNCTION public.fn_search_public_course_catalogue(
    p_search       TEXT DEFAULT NULL,
    p_category_id  BIGINT DEFAULT NULL,
    p_difficulty   VARCHAR DEFAULT NULL,
    p_sort         VARCHAR DEFAULT 'relevance',
    p_limit        INTEGER DEFAULT 12,
    p_offset       INTEGER DEFAULT 0
)
RETURNS TABLE (
    course_id          BIGINT,
    title              VARCHAR,
    slug               VARCHAR,
    short_description  VARCHAR,
    thumbnail_url      TEXT,
    difficulty         VARCHAR,
    category_id        BIGINT,
    category_name      VARCHAR,
    avg_rating         NUMERIC,
    review_count       INTEGER,
    published_at       TIMESTAMPTZ,
    rank_score         REAL,
    total_count        BIGINT
)
LANGUAGE SQL
STABLE
AS $$
    WITH search_parameters AS (
        SELECT
            CASE
                WHEN p_search IS NULL
                     OR BTRIM(p_search) = ''
                    THEN NULL
                ELSE WEBSEARCH_TO_TSQUERY(
                    'english',
                    BTRIM(p_search)
                )
            END AS search_query
    ),

    filtered_courses AS (
        SELECT
            c.id AS course_id,
            c.title,
            c.slug,
            c.short_description,
            c.thumbnail_url,
            c.difficulty,
            c.category_id,

            COALESCE(
                cat.name,
                'Uncategorized'
            )::VARCHAR AS category_name,

            c.avg_rating,
            c.review_count,
            c.published_at,

            CASE
                WHEN sp.search_query IS NULL
                    THEN 0.0::REAL
                ELSE TS_RANK_CD(
                    c.search_vector,
                    sp.search_query
                )::REAL
            END AS rank_score

        FROM public.courses c

        LEFT JOIN public.categories cat
            ON cat.id = c.category_id

        CROSS JOIN search_parameters sp

        WHERE
            -- Public catalogue shows published courses only.
            c.status = 'PUBLISHED'

            -- Courses belonging to inactive categories are hidden.
            AND (
                c.category_id IS NULL
                OR cat.is_active = TRUE
            )

            -- Optional category filter.
            AND (
                p_category_id IS NULL
                OR c.category_id = p_category_id
            )

            -- Optional difficulty filter.
            AND (
                p_difficulty IS NULL
                OR BTRIM(p_difficulty) = ''
                OR c.difficulty = UPPER(BTRIM(p_difficulty))
            )

            -- Optional PostgreSQL full-text keyword search.
            AND (
                sp.search_query IS NULL
                OR c.search_vector @@ sp.search_query
            )
    )

    SELECT
        fc.course_id,
        fc.title,
        fc.slug,
        fc.short_description,
        fc.thumbnail_url,
        fc.difficulty,
        fc.category_id,
        fc.category_name,
        fc.avg_rating,
        fc.review_count,
        fc.published_at,
        fc.rank_score,

        COUNT(*) OVER () AS total_count

    FROM filtered_courses fc

    ORDER BY
        -- Search relevance when a keyword is present.
        CASE
            WHEN LOWER(COALESCE(p_sort, 'relevance')) = 'relevance'
                 AND p_search IS NOT NULL
                 AND BTRIM(p_search) <> ''
                THEN fc.rank_score
        END DESC,

        -- Without a search word, relevance sorting uses newest first.
        CASE
            WHEN LOWER(COALESCE(p_sort, 'relevance')) = 'relevance'
                 AND (
                     p_search IS NULL
                     OR BTRIM(p_search) = ''
                 )
                THEN fc.published_at
        END DESC NULLS LAST,

        -- Highest rating first.
        CASE
            WHEN LOWER(COALESCE(p_sort, 'relevance')) = 'rating'
                THEN fc.avg_rating
        END DESC,

        CASE
            WHEN LOWER(COALESCE(p_sort, 'relevance')) = 'rating'
                THEN fc.review_count
        END DESC,

        -- Newest published course first.
        CASE
            WHEN LOWER(COALESCE(p_sort, 'relevance')) = 'newest'
                THEN fc.published_at
        END DESC NULLS LAST,

        -- Alphabetical title sorting.
        CASE
            WHEN LOWER(COALESCE(p_sort, 'relevance')) = 'title'
                THEN LOWER(fc.title)
        END ASC,

        -- Stable final ordering.
        fc.course_id ASC

    LIMIT
        LEAST(
            GREATEST(
                COALESCE(p_limit, 12),
                1
            ),
            50
        )

    OFFSET
        GREATEST(
            COALESCE(p_offset, 0),
            0
        );
$$;


COMMENT ON FUNCTION public.fn_search_public_course_catalogue(
    TEXT,
    BIGINT,
    VARCHAR,
    VARCHAR,
    INTEGER,
    INTEGER
)
IS
'Returns published courses with PostgreSQL full-text search, category and difficulty filtering, sorting, pagination and total count.';