-- =========================================================
-- V13: Notifications
--
-- All schema for the notification feature in one file:
--   * the notifications table (per-user inbox)
--   * fn_create_notification -- the insert helper
--   * sp_mark_notification_read / sp_mark_all_read -- read state
--   * lifecycle triggers that notify students when certificates are
--     issued and courses are completed
--   * notification indexes
-- =========================================================

-- =========================================================
-- 1. Notifications table
-- =========================================================

CREATE TABLE public.notifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT NOT NULL,
    message            TEXT NOT NULL,
    is_read            BOOLEAN NOT NULL DEFAULT FALSE,
    related_entity_type VARCHAR(50),
    related_entity_id  BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notifications
        PRIMARY KEY (id),

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_notifications_message_not_blank
        CHECK (btrim(message) <> '')
);


-- =========================================================
-- 2. Write helpers
-- =========================================================

CREATE OR REPLACE FUNCTION public.fn_create_notification(
    p_user_id           BIGINT,
    p_message           TEXT,
    p_related_entity_type VARCHAR DEFAULT NULL,
    p_related_entity_id BIGINT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_notification_id BIGINT;
BEGIN
    INSERT INTO public.notifications (
        user_id,
        message,
        related_entity_type,
        related_entity_id
    )
    VALUES (
        p_user_id,
        p_message,
        p_related_entity_type,
        p_related_entity_id
    )
    RETURNING public.notifications.id
    INTO v_notification_id;

    RETURN v_notification_id;
END;
$$;

-- Marks one notification read, but only when it belongs to the caller.
CREATE OR REPLACE FUNCTION public.sp_mark_notification_read(
    p_notification_id BIGINT,
    p_user_id         BIGINT
)
RETURNS TABLE (notification_id BIGINT)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.notifications
    SET is_read = TRUE
    WHERE id = p_notification_id
      AND user_id = p_user_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'LTNF1: Notification % does not exist for this user.', p_notification_id
            USING ERRCODE = 'LTNF1';
    END IF;

    notification_id := p_notification_id;
    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE = 'LTNF1' THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_mark_notification_read unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while updating the notification: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;

CREATE OR REPLACE FUNCTION public.sp_mark_all_notifications_read(p_user_id BIGINT)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_updated BIGINT;
BEGIN
    UPDATE public.notifications
    SET is_read = TRUE
    WHERE user_id = p_user_id
      AND is_read = FALSE;

    GET DIAGNOSTICS v_updated = ROW_COUNT;

    RETURN v_updated;
END;
$$;


-- =========================================================
-- 3. Lifecycle notification triggers
-- =========================================================

-- Notify the holder the moment a certificate is issued.
CREATE OR REPLACE FUNCTION public.fn_notify_certificate_issued()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_entity_title TEXT;
BEGIN
    IF NEW.type = 'course' THEN
        SELECT title INTO v_entity_title
        FROM public.courses WHERE id = NEW.course_id;
    ELSE
        SELECT title INTO v_entity_title
        FROM public.tracks WHERE id = NEW.track_id;
    END IF;

    PERFORM public.fn_create_notification(
        NEW.user_id,
        'Congratulations! Your certificate for "'
        || COALESCE(v_entity_title, 'your completed learning path')
        || '" has been issued.'
        || ' Verification code: ' || NEW.cert_code || '.',
        'certificate',
        NEW.id
    );

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_certificate_issued ON public.certificates;
CREATE TRIGGER trg_notify_certificate_issued
AFTER INSERT ON public.certificates
FOR EACH ROW
EXECUTE FUNCTION public.fn_notify_certificate_issued();

-- Notify the student when a course enrollment is completed.
CREATE OR REPLACE FUNCTION public.fn_notify_course_completed()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_course_title TEXT;
BEGIN
    SELECT title INTO v_course_title
    FROM public.courses WHERE id = NEW.course_id;

    PERFORM public.fn_create_notification(
        NEW.user_id,
        'You completed the course "'
        || COALESCE(v_course_title, 'a course')
        || '". Your certificate is on the way!',
        'course',
        NEW.course_id
    );

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_course_completed ON public.enrollments;
CREATE TRIGGER trg_notify_course_completed
AFTER UPDATE OF status ON public.enrollments
FOR EACH ROW
WHEN (NEW.status = 'completed' AND OLD.status IS DISTINCT FROM 'completed')
EXECUTE FUNCTION public.fn_notify_course_completed();


-- =========================================================
-- 4. Notification indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_notifications_user_created
    ON public.notifications (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read
    ON public.notifications (user_id, is_read);
