-- =========================================================
-- V14: Audit logging
--
-- All schema for the audit feature in one file:
--   * the audit_logs table (append-only, JSONB before/after values)
--   * fn_write_audit -- the write helper
--   * fn_audit_trigger -- the generic audit trigger attached to the
--     security- and business-critical tables
--   * the trigger attachments (roles, course lifecycle, enrollment,
--     prerequisites, reviews, certificates)
--   * audit indexes
--
-- performed_by resolves from the application session setting
-- 'app.user_id' (set per-request by the backend connection); when the
-- setting is absent (direct psql, seed scripts) it stays NULL.
-- =========================================================

-- =========================================================
-- 1. Audit log table
-- =========================================================

CREATE TABLE public.audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    table_name   VARCHAR(100) NOT NULL,
    record_id    BIGINT NOT NULL,
    action       VARCHAR(50) NOT NULL,
    old_values   JSONB,
    new_values   JSONB,
    performed_by BIGINT,
    performed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_audit_logs
        PRIMARY KEY (id),

    CONSTRAINT fk_audit_logs_performed_by
        FOREIGN KEY (performed_by)
        REFERENCES public.users (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_audit_logs_action
        CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'GRANT_ROLE', 'REVOKE_ROLE'))
);


-- =========================================================
-- 2. Write helper
-- =========================================================

CREATE OR REPLACE FUNCTION public.fn_write_audit(
    p_table_name   VARCHAR,
    p_record_id    BIGINT,
    p_action       VARCHAR,
    p_old_values   JSONB,
    p_new_values   JSONB,
    p_performed_by BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_audit_id BIGINT;
BEGIN
    INSERT INTO public.audit_logs (
        table_name,
        record_id,
        action,
        old_values,
        new_values,
        performed_by
    )
    VALUES (
        p_table_name,
        p_record_id,
        p_action,
        p_old_values,
        p_new_values,
        p_performed_by
    )
    RETURNING public.audit_logs.id
    INTO v_audit_id;

    RETURN v_audit_id;
END;
$$;

-- Resolves the acting user from the 'app.user_id' session setting.
CREATE OR REPLACE FUNCTION public.fn_audit_actor()
RETURNS BIGINT
LANGUAGE sql
STABLE
AS $$
    SELECT NULLIF(current_setting('app.user_id', TRUE), '')::BIGINT;
$$;


-- =========================================================
-- 3. Generic audit trigger
-- =========================================================

CREATE OR REPLACE FUNCTION public.fn_audit_trigger()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_actor   BIGINT;
    v_action  VARCHAR(50);
    v_table   VARCHAR(100);
    v_record  BIGINT;
    v_old_json JSONB;
    v_new_json JSONB;
BEGIN
    v_actor := public.fn_audit_actor();

    IF TG_OP = 'INSERT' THEN
        v_action := 'INSERT';
        v_record := NEW.id;
        v_new_json := TO_JSONB(NEW);
    ELSIF TG_OP = 'UPDATE' THEN
        v_action := 'UPDATE';
        v_record := NEW.id;
        v_old_json := TO_JSONB(OLD);
        v_new_json := TO_JSONB(NEW);
    ELSE
        v_action := 'DELETE';
        v_record := OLD.id;
        v_old_json := TO_JSONB(OLD);
    END IF;

    -- Role grants/revokes are recorded with their own action names so
    -- administrators can audit permission changes specifically.
    IF TG_TABLE_NAME = 'user_roles' THEN
        IF v_action = 'INSERT' THEN
            v_action := 'GRANT_ROLE';
        ELSIF v_action = 'DELETE' THEN
            v_action := 'REVOKE_ROLE';
        END IF;
    END IF;

    PERFORM public.fn_write_audit(
        TG_TABLE_NAME,
        v_record,
        v_action,
        v_old_json,
        v_new_json,
        v_actor
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;


-- =========================================================
-- 4. Audit trigger attachments
-- =========================================================

DROP TRIGGER IF EXISTS trg_audit_user_roles ON public.user_roles;
CREATE TRIGGER trg_audit_user_roles
AFTER INSERT OR UPDATE OR DELETE ON public.user_roles
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_audit_instructor_requests ON public.instructor_requests;
CREATE TRIGGER trg_audit_instructor_requests
AFTER INSERT OR UPDATE OR DELETE ON public.instructor_requests
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_audit_courses ON public.courses;
CREATE TRIGGER trg_audit_courses
AFTER INSERT OR UPDATE OR DELETE ON public.courses
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_audit_enrollments ON public.enrollments;
CREATE TRIGGER trg_audit_enrollments
AFTER INSERT OR UPDATE OR DELETE ON public.enrollments
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_audit_course_prerequisites ON public.course_prerequisites;
CREATE TRIGGER trg_audit_course_prerequisites
AFTER INSERT OR UPDATE OR DELETE ON public.course_prerequisites
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_audit_reviews ON public.reviews;
CREATE TRIGGER trg_audit_reviews
AFTER INSERT OR UPDATE OR DELETE ON public.reviews
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();

DROP TRIGGER IF EXISTS trg_audit_certificates ON public.certificates;
CREATE TRIGGER trg_audit_certificates
AFTER INSERT OR UPDATE OR DELETE ON public.certificates
FOR EACH ROW
EXECUTE FUNCTION public.fn_audit_trigger();


-- =========================================================
-- 5. Audit indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_audit_logs_table_record
    ON public.audit_logs (table_name, record_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_performed_at
    ON public.audit_logs (performed_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor
    ON public.audit_logs (performed_by);
