-- =========================================================
-- V10: Quiz engine
--
-- All schema for the quiz feature in one file:
--   * lesson quizzes, questions and options
--   * regular quiz attempts (per enrollment) with a random question
--     snapshot and per-question answers
--   * bypass quiz attempts (passing a prerequisite course quiz to
--     satisfy that prerequisite without completing the course)
--   * quiz_submissions -- a history of graded attempts per user/quiz
--   * sp_start_quiz_attempt / sp_start_bypass_attempt /
--     sp_submit_quiz_attempt -- the grading flow
--   * vw_quiz_public -- sanitized questions/options for taking a quiz
--   * quiz indexes + demo seed quizzes
--
-- A passed bypass attempt inserts a row into public.course_bypasses,
-- which satisfies the prerequisite (V9) and fires the V9
-- trg_unlock_course_after_bypass trigger that unlocks course content.
-- =========================================================

-- =========================================================
-- 1. Quiz content
-- =========================================================

CREATE TABLE public.quizzes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lesson_id            BIGINT NOT NULL,
    title                VARCHAR(255) NOT NULL,
    passing_score        NUMERIC(5,2) NOT NULL DEFAULT 60.00,
    questions_per_attempt INTEGER NOT NULL DEFAULT 5,
    daily_attempt_limit  INTEGER NOT NULL DEFAULT 3,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_quizzes
        PRIMARY KEY (id),

    CONSTRAINT uq_quizzes_lesson
        UNIQUE (lesson_id),

    CONSTRAINT fk_quizzes_lesson
        FOREIGN KEY (lesson_id)
        REFERENCES public.lessons (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_quizzes_title_not_blank
        CHECK (btrim(title) <> ''),

    CONSTRAINT chk_quizzes_passing_score
        CHECK (passing_score >= 0 AND passing_score <= 100),

    CONSTRAINT chk_quizzes_questions_per_attempt
        CHECK (questions_per_attempt > 0),

    CONSTRAINT chk_quizzes_daily_attempt_limit
        CHECK (daily_attempt_limit >= 1)
);

CREATE TRIGGER trg_quizzes_set_updated_at
BEFORE UPDATE ON public.quizzes
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.quiz_questions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quiz_id        BIGINT NOT NULL,
    question_text  TEXT NOT NULL,
    sequence_order INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_quiz_questions
        PRIMARY KEY (id),

    CONSTRAINT uq_quiz_questions_quiz_sequence
        UNIQUE (quiz_id, sequence_order),

    CONSTRAINT fk_quiz_questions_quiz
        FOREIGN KEY (quiz_id)
        REFERENCES public.quizzes (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_quiz_questions_text_not_blank
        CHECK (btrim(question_text) <> '')
);

CREATE TRIGGER trg_quiz_questions_set_updated_at
BEFORE UPDATE ON public.quiz_questions
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.quiz_options (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id  BIGINT NOT NULL,
    option_label VARCHAR(5) NOT NULL,
    option_text  TEXT NOT NULL,
    is_correct   BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_quiz_options
        PRIMARY KEY (id),

    CONSTRAINT uq_quiz_options_question_label
        UNIQUE (question_id, option_label),

    CONSTRAINT fk_quiz_options_question
        FOREIGN KEY (question_id)
        REFERENCES public.quiz_questions (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_quiz_options_label_not_blank
        CHECK (btrim(option_label) <> ''),

    CONSTRAINT chk_quiz_options_text_not_blank
        CHECK (btrim(option_text) <> '')
);


-- =========================================================
-- 2. Regular quiz attempts (per enrollment)
-- =========================================================

CREATE TABLE public.quiz_attempts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    enrollment_id BIGINT NOT NULL,
    quiz_id      BIGINT NOT NULL,
    attempt_date DATE NOT NULL DEFAULT CURRENT_DATE,
    attempt_no   INTEGER NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'in_progress',
    started_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMPTZ,
    score_pct    NUMERIC(5,2),
    passed       BOOLEAN,

    CONSTRAINT pk_quiz_attempts
        PRIMARY KEY (id),

    CONSTRAINT uq_quiz_attempts_enrollment_quiz_date_no
        UNIQUE (enrollment_id, quiz_id, attempt_date, attempt_no),

    CONSTRAINT fk_quiz_attempts_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES public.enrollments (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_quiz_attempts_quiz
        FOREIGN KEY (quiz_id)
        REFERENCES public.quizzes (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_quiz_attempts_status
        CHECK (status IN ('in_progress', 'submitted')),

    CONSTRAINT chk_quiz_attempts_score
        CHECK (score_pct IS NULL OR (score_pct >= 0 AND score_pct <= 100))
);

-- Question snapshot: which questions were drawn for this attempt.
CREATE TABLE public.quiz_attempt_questions (
    attempt_id  BIGINT NOT NULL,
    question_id BIGINT NOT NULL,

    CONSTRAINT pk_quiz_attempt_questions
        PRIMARY KEY (attempt_id, question_id),

    CONSTRAINT fk_quiz_attempt_questions_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES public.quiz_attempts (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_quiz_attempt_questions_question
        FOREIGN KEY (question_id)
        REFERENCES public.quiz_questions (id)
        ON DELETE CASCADE
);

CREATE TABLE public.attempt_answers (
    attempt_id         BIGINT NOT NULL,
    question_id        BIGINT NOT NULL,
    selected_option_id BIGINT NOT NULL,
    is_correct         BOOLEAN,
    answered_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_attempt_answers
        PRIMARY KEY (attempt_id, question_id),

    CONSTRAINT fk_attempt_answers_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES public.quiz_attempts (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attempt_answers_question
        FOREIGN KEY (question_id)
        REFERENCES public.quiz_questions (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attempt_answers_option
        FOREIGN KEY (selected_option_id)
        REFERENCES public.quiz_options (id)
        ON DELETE CASCADE
);

-- Graded history per user/quiz (best/current score) for progress reads.
CREATE TABLE public.quiz_submissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT NOT NULL,
    quiz_id      BIGINT NOT NULL,
    score_pct    NUMERIC(5,2) NOT NULL,
    passed       BOOLEAN NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_quiz_submissions
        PRIMARY KEY (id),

    CONSTRAINT fk_quiz_submissions_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_quiz_submissions_quiz
        FOREIGN KEY (quiz_id)
        REFERENCES public.quizzes (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_quiz_submissions_score
        CHECK (score_pct >= 0 AND score_pct <= 100)
);


-- =========================================================
-- 3. Bypass quiz attempts
-- =========================================================

-- A bypass attempt lets a student pass the quiz of a prerequisite
-- course to satisfy that prerequisite without completing the course.
-- A passing attempt writes a course_bypasses row for
-- (user, target_course, prerequisite_course).
CREATE TABLE public.bypass_attempts (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                BIGINT NOT NULL,
    target_course_id       BIGINT NOT NULL,
    prerequisite_course_id BIGINT NOT NULL,
    attempt_date           DATE NOT NULL DEFAULT CURRENT_DATE,
    attempt_no             INTEGER NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'in_progress',
    started_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at           TIMESTAMPTZ,
    score_pct              NUMERIC(5,2),
    passed                 BOOLEAN,

    CONSTRAINT pk_bypass_attempts
        PRIMARY KEY (id),

    CONSTRAINT uq_bypass_attempts_user_target_prereq_date_no
        UNIQUE (user_id, target_course_id, prerequisite_course_id, attempt_date, attempt_no),

    CONSTRAINT fk_bypass_attempts_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bypass_attempts_target
        FOREIGN KEY (target_course_id)
        REFERENCES public.courses (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bypass_attempts_prerequisite
        FOREIGN KEY (prerequisite_course_id)
        REFERENCES public.courses (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_bypass_attempts_status
        CHECK (status IN ('in_progress', 'submitted')),

    CONSTRAINT chk_bypass_attempts_score
        CHECK (score_pct IS NULL OR (score_pct >= 0 AND score_pct <= 100))
);

CREATE TABLE public.bypass_attempt_questions (
    attempt_id         BIGINT NOT NULL,
    source_question_id BIGINT NOT NULL,

    CONSTRAINT pk_bypass_attempt_questions
        PRIMARY KEY (attempt_id, source_question_id),

    CONSTRAINT fk_bypass_attempt_questions_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES public.bypass_attempts (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bypass_attempt_questions_question
        FOREIGN KEY (source_question_id)
        REFERENCES public.quiz_questions (id)
        ON DELETE CASCADE
);

CREATE TABLE public.bypass_attempt_answers (
    attempt_id         BIGINT NOT NULL,
    source_question_id BIGINT NOT NULL,
    selected_option_id BIGINT NOT NULL,
    is_correct         BOOLEAN,
    answered_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_bypass_attempt_answers
        PRIMARY KEY (attempt_id, source_question_id),

    CONSTRAINT fk_bypass_attempt_answers_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES public.bypass_attempts (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bypass_attempt_answers_question
        FOREIGN KEY (source_question_id)
        REFERENCES public.quiz_questions (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bypass_attempt_answers_option
        FOREIGN KEY (selected_option_id)
        REFERENCES public.quiz_options (id)
        ON DELETE CASCADE
);


-- =========================================================
-- 4. Question sampling
-- =========================================================

-- Draws p_count random questions from a quiz's question bank.
CREATE OR REPLACE FUNCTION public.fn_quiz_pick_questions(
    p_quiz_id BIGINT,
    p_count   INTEGER
)
RETURNS TABLE (question_id BIGINT)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT q.id
    FROM public.quiz_questions q
    WHERE q.quiz_id = p_quiz_id
    ORDER BY RANDOM()
    LIMIT GREATEST(COALESCE(p_count, 1), 1);
END;
$$;

-- Sanitized question bank for taking a quiz (options, but never the
-- is_correct flag).
CREATE OR REPLACE VIEW public.vw_quiz_public AS
SELECT
    q.id                  AS quiz_id,
    q.lesson_id,
    q.title               AS quiz_title,
    q.passing_score,
    q.questions_per_attempt,
    qq.id                 AS question_id,
    qq.question_text,
    qq.sequence_order,
    COALESCE(
        JSONB_AGG(
            JSONB_BUILD_OBJECT(
                'option_id',     qo.id,
                'option_label',  qo.option_label,
                'option_text',   qo.option_text
            )
            ORDER BY qo.option_label
        ) FILTER (WHERE qo.id IS NOT NULL),
        '[]'::JSONB
    )                     AS options
FROM public.quizzes q
JOIN public.quiz_questions qq ON qq.quiz_id = q.id
LEFT JOIN public.quiz_options qo ON qo.question_id = qq.id
GROUP BY q.id, q.lesson_id, q.title, q.passing_score,
         q.questions_per_attempt, qq.id, qq.question_text, qq.sequence_order;


-- =========================================================
-- 5. Attempt lifecycle procedures
-- =========================================================

-- Starts a regular quiz attempt for an enrollment. Enforces the daily
-- attempt limit and snapshots the drawn questions.
CREATE OR REPLACE FUNCTION public.sp_start_quiz_attempt(
    p_enrollment_id BIGINT,
    p_quiz_id       BIGINT
)
RETURNS TABLE (
    attempt_id     BIGINT,
    quiz_id        BIGINT,
    enrollment_id  BIGINT,
    attempt_no     INTEGER,
    started_at     TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_attempt_no        INTEGER;
    v_questions_per     INTEGER;
    v_today_attempts    INTEGER;
    v_enrollment_status VARCHAR(20);
BEGIN
    SELECT e.status
    INTO v_enrollment_status
    FROM public.enrollments e
    WHERE e.id = p_enrollment_id;

    IF v_enrollment_status IS NULL THEN
        RAISE EXCEPTION 'LTQ01: Enrollment % does not exist.', p_enrollment_id
            USING ERRCODE = 'LTQ01';
    END IF;

    IF v_enrollment_status <> 'active' THEN
        RAISE EXCEPTION 'LTQ02: Only active enrollments can take quizzes.'
            USING ERRCODE = 'LTQ02';
    END IF;

    SELECT q.questions_per_attempt
    INTO v_questions_per
    FROM public.quizzes q
    WHERE q.id = p_quiz_id;

    IF v_questions_per IS NULL THEN
        RAISE EXCEPTION 'LTQ03: Quiz % does not exist.', p_quiz_id
            USING ERRCODE = 'LTQ03';
    END IF;

    SELECT COUNT(*)
    INTO v_today_attempts
    FROM public.quiz_attempts
    WHERE enrollment_id = p_enrollment_id
      AND quiz_id = p_quiz_id
      AND attempt_date = CURRENT_DATE;

    SELECT COALESCE(MAX(attempt_no), 0) + 1
    INTO v_attempt_no
    FROM public.quiz_attempts
    WHERE enrollment_id = p_enrollment_id
      AND quiz_id = p_quiz_id
      AND attempt_date = CURRENT_DATE;

    IF v_today_attempts >= (
        SELECT daily_attempt_limit
        FROM public.quizzes
        WHERE id = p_quiz_id
    ) THEN
        RAISE EXCEPTION 'LTQ04: Daily attempt limit for this quiz was reached.'
            USING ERRCODE = 'LTQ04';
    END IF;

    INSERT INTO public.quiz_attempts (enrollment_id, quiz_id, attempt_date, attempt_no)
    VALUES (p_enrollment_id, p_quiz_id, CURRENT_DATE, v_attempt_no)
    RETURNING
        public.quiz_attempts.id,
        public.quiz_attempts.quiz_id,
        public.quiz_attempts.enrollment_id,
        public.quiz_attempts.attempt_no,
        public.quiz_attempts.started_at
    INTO attempt_id, quiz_id, enrollment_id, attempt_no, started_at;

    INSERT INTO public.quiz_attempt_questions (attempt_id, question_id)
    SELECT attempt_id, qq.question_id
    FROM public.fn_quiz_pick_questions(p_quiz_id, v_questions_per) qq;

    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE IN ('LTQ01', 'LTQ02', 'LTQ03', 'LTQ04') THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_start_quiz_attempt unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while starting the quiz: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;

-- Starts a bypass attempt: passing the quiz of a prerequisite course
-- to unlock a target course without completing the prerequisite.
CREATE OR REPLACE FUNCTION public.sp_start_bypass_attempt(
    p_user_id                BIGINT,
    p_target_course_id       BIGINT,
    p_prerequisite_course_id BIGINT
)
RETURNS TABLE (
    attempt_id             BIGINT,
    target_course_id       BIGINT,
    prerequisite_course_id BIGINT,
    attempt_no             INTEGER,
    started_at             TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_attempt_no     INTEGER;
    v_quiz_id        BIGINT;
    v_questions_per  INTEGER;
    v_is_prerequisite BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM public.course_prerequisites
        WHERE course_id = p_target_course_id
          AND prerequisite_course_id = p_prerequisite_course_id
    )
    INTO v_is_prerequisite;

    IF NOT v_is_prerequisite THEN
        RAISE EXCEPTION 'LTP01: Course % is not a prerequisite of course %.',
            p_prerequisite_course_id, p_target_course_id
            USING ERRCODE = 'LTP01';
    END IF;

    -- Bypass quizzes use a quiz from the prerequisite course.
    SELECT q.id, q.questions_per_attempt
    INTO v_quiz_id, v_questions_per
    FROM public.quizzes q
    JOIN public.lessons l ON l.id = q.lesson_id
    WHERE l.course_id = p_prerequisite_course_id
    ORDER BY l.sequence_order ASC, q.id ASC
    LIMIT 1;

    IF v_quiz_id IS NULL THEN
        RAISE EXCEPTION 'LTQ03: Prerequisite course % has no quiz to bypass with.',
            p_prerequisite_course_id
            USING ERRCODE = 'LTQ03';
    END IF;

    SELECT COALESCE(MAX(attempt_no), 0) + 1
    INTO v_attempt_no
    FROM public.bypass_attempts
    WHERE user_id = p_user_id
      AND target_course_id = p_target_course_id
      AND prerequisite_course_id = p_prerequisite_course_id
      AND attempt_date = CURRENT_DATE;

    INSERT INTO public.bypass_attempts (
        user_id,
        target_course_id,
        prerequisite_course_id,
        attempt_date,
        attempt_no
    )
    VALUES (
        p_user_id,
        p_target_course_id,
        p_prerequisite_course_id,
        CURRENT_DATE,
        v_attempt_no
    )
    RETURNING
        public.bypass_attempts.id,
        public.bypass_attempts.target_course_id,
        public.bypass_attempts.prerequisite_course_id,
        public.bypass_attempts.attempt_no,
        public.bypass_attempts.started_at
    INTO attempt_id, target_course_id, prerequisite_course_id, attempt_no, started_at;

    INSERT INTO public.bypass_attempt_questions (attempt_id, source_question_id)
    SELECT attempt_id, qq.question_id
    FROM public.fn_quiz_pick_questions(v_quiz_id, v_questions_per) qq;

    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE IN ('LTP01', 'LTQ03') THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_start_bypass_attempt unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while starting the bypass quiz: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;

-- Grades a submitted attempt. Correct answers are recorded on the
-- attempt_answers / bypass_attempt_answers rows; the grade is the share
-- of correctly answered questions among the snapshot.
--
--   regular attempt (p_bypass_quiz = FALSE):
--     * writes quiz_submissions history
--     * keeps the best score on enrollments.final_score_pct
--   bypass attempt (p_bypass_quiz = TRUE):
--     * a passing score (>= 60%) inserts a course_bypasses row, which
--       satisfies the prerequisite (V9) and fires the V9 unlock trigger
CREATE OR REPLACE FUNCTION public.sp_submit_quiz_attempt(
    p_attempt_id  BIGINT,
    p_bypass_quiz BOOLEAN
)
RETURNS TABLE (
    attempt_id BIGINT,
    status     VARCHAR(20),
    score_pct  NUMERIC(5,2),
    passed     BOOLEAN,
    submitted_at TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_total       INTEGER;
    v_correct     INTEGER;
    v_score       NUMERIC(5,2);
    v_passed      BOOLEAN;
    v_passing     NUMERIC(5,2) := 60.00;
    v_user_id     BIGINT;
    v_target      BIGINT;
    v_prereq      BIGINT;
    v_enrollment  BIGINT;
BEGIN
    IF p_bypass_quiz THEN
        SELECT ba.id, ba.user_id, ba.target_course_id, ba.prerequisite_course_id, ba.status
        INTO attempt_id, v_user_id, v_target, v_prereq, status
        FROM public.bypass_attempts ba
        WHERE ba.id = p_attempt_id;
    ELSE
        SELECT qa.id, qa.enrollment_id, qa.status
        INTO attempt_id, v_enrollment, status
        FROM public.quiz_attempts qa
        WHERE qa.id = p_attempt_id;
    END IF;

    IF attempt_id IS NULL THEN
        RAISE EXCEPTION 'LTQ01: Attempt % does not exist.', p_attempt_id
            USING ERRCODE = 'LTQ01';
    END IF;

    IF status = 'submitted' THEN
        RAISE EXCEPTION 'LTQ05: Attempt % was already submitted.', p_attempt_id
            USING ERRCODE = 'LTQ05';
    END IF;

    IF p_bypass_quiz THEN
        SELECT COUNT(*),
               COUNT(*) FILTER (WHERE aa.is_correct)
        INTO v_total, v_correct
        FROM public.bypass_attempt_questions baq
        LEFT JOIN public.bypass_attempt_answers aa
               ON aa.attempt_id = baq.attempt_id
              AND aa.source_question_id = baq.source_question_id
        WHERE baq.attempt_id = p_attempt_id;
    ELSE
        SELECT COUNT(*),
               COUNT(*) FILTER (WHERE aa.is_correct)
        INTO v_total, v_correct
        FROM public.quiz_attempt_questions qaq
        LEFT JOIN public.attempt_answers aa
               ON aa.attempt_id = qaq.attempt_id
              AND aa.question_id = qaq.question_id
        WHERE qaq.attempt_id = p_attempt_id;
    END IF;

    IF v_total IS NULL OR v_total = 0 THEN
        RAISE EXCEPTION 'LTQ06: Attempt % has no answered questions.', p_attempt_id
            USING ERRCODE = 'LTQ06';
    END IF;

    v_score := ROUND((v_correct::NUMERIC / v_total::NUMERIC) * 100, 2);

    IF p_bypass_quiz THEN
        -- Bypass quizzes always pass at the standard 60% threshold.
        v_passed := v_score >= v_passing;
    ELSE
        SELECT q.passing_score
        INTO v_passing
        FROM public.quizzes q
        JOIN public.quiz_attempts qa ON qa.quiz_id = q.id
        WHERE qa.id = p_attempt_id;

        v_passed := v_score >= COALESCE(v_passing, 60.00);
    END IF;

    IF p_bypass_quiz THEN
        UPDATE public.bypass_attempts
        SET status = 'submitted',
            submitted_at = CURRENT_TIMESTAMP,
            score_pct = v_score,
            passed = v_passed
        WHERE id = p_attempt_id;

        IF v_passed THEN
            INSERT INTO public.course_bypasses (user_id, target_course_id, prerequisite_course_id)
            VALUES (v_user_id, v_target, v_prereq)
            ON CONFLICT (user_id, target_course_id, prerequisite_course_id) DO NOTHING;
        END IF;
    ELSE
        UPDATE public.quiz_attempts
        SET status = 'submitted',
            submitted_at = CURRENT_TIMESTAMP,
            score_pct = v_score,
            passed = v_passed
        WHERE id = p_attempt_id;

        INSERT INTO public.quiz_submissions (user_id, quiz_id, score_pct, passed)
        SELECT e.user_id, qa.quiz_id, v_score, v_passed
        FROM public.quiz_attempts qa
        JOIN public.enrollments e ON e.id = qa.enrollment_id
        WHERE qa.id = p_attempt_id;

        -- Keep the best score as the enrollment's final score.
        UPDATE public.enrollments e
        SET final_score_pct = GREATEST(
                COALESCE(e.final_score_pct, v_score),
                v_score
            )
        FROM public.quiz_attempts qa
        WHERE qa.id = p_attempt_id
          AND e.id = qa.enrollment_id;
    END IF;

    score_pct := v_score;
    passed := v_passed;
    submitted_at := CURRENT_TIMESTAMP;
    status := 'submitted';
    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE IN ('LTQ01', 'LTQ05', 'LTQ06') THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_submit_quiz_attempt unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while submitting the quiz: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;

-- Records the option a student picked for one question of an attempt.
CREATE OR REPLACE FUNCTION public.sp_answer_quiz_question(
    p_attempt_id         BIGINT,
    p_question_id        BIGINT,
    p_selected_option_id BIGINT,
    p_bypass_quiz        BOOLEAN
)
RETURNS TABLE (
    attempt_id  BIGINT,
    question_id BIGINT,
    is_correct  BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_correct BOOLEAN;
BEGIN
    SELECT qo.is_correct
    INTO v_correct
    FROM public.quiz_options qo
    WHERE qo.id = p_selected_option_id
      AND qo.question_id = p_question_id;

    IF v_correct IS NULL THEN
        RAISE EXCEPTION 'LTQ07: Option % does not belong to question %.',
            p_selected_option_id, p_question_id
            USING ERRCODE = 'LTQ07';
    END IF;

    IF p_bypass_quiz THEN
        INSERT INTO public.bypass_attempt_answers (
            attempt_id,
            source_question_id,
            selected_option_id,
            is_correct
        )
        VALUES (p_attempt_id, p_question_id, p_selected_option_id, v_correct)
        ON CONFLICT (attempt_id, source_question_id) DO UPDATE
            SET selected_option_id = EXCLUDED.selected_option_id,
                is_correct = EXCLUDED.is_correct,
                answered_at = CURRENT_TIMESTAMP;
    ELSE
        INSERT INTO public.attempt_answers (
            attempt_id,
            question_id,
            selected_option_id,
            is_correct
        )
        VALUES (p_attempt_id, p_question_id, p_selected_option_id, v_correct)
        ON CONFLICT (attempt_id, question_id) DO UPDATE
            SET selected_option_id = EXCLUDED.selected_option_id,
                is_correct = EXCLUDED.is_correct,
                answered_at = CURRENT_TIMESTAMP;
    END IF;

    attempt_id := p_attempt_id;
    question_id := p_question_id;
    is_correct := v_correct;
    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE IN ('LTQ07', 'LTQ01') THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_answer_quiz_question unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while saving the answer: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;


-- =========================================================
-- 6. Quiz indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_quiz_questions_quiz
    ON public.quiz_questions (quiz_id);

CREATE INDEX IF NOT EXISTS idx_quiz_options_question
    ON public.quiz_options (question_id);

CREATE INDEX IF NOT EXISTS idx_quiz_attempts_enrollment_quiz
    ON public.quiz_attempts (enrollment_id, quiz_id);

CREATE INDEX IF NOT EXISTS idx_quiz_submissions_user_quiz
    ON public.quiz_submissions (user_id, quiz_id);

CREATE INDEX IF NOT EXISTS idx_bypass_attempts_user_target
    ON public.bypass_attempts (user_id, target_course_id);


-- =========================================================
-- 7. Demo seed quizzes
--
-- Two quizzes on Database Design Fundamentals (course 1) and one on
-- SQL & Query Optimization (course 2). The course-1 quizzes double as
-- the bypass bank for course 2 (course 2 requires course 1 in V9).
-- Lesson ids refer to the V8 demo lessons. Idempotent seed: guarded
-- by the unique constraints / ON CONFLICT.
-- =========================================================

INSERT INTO public.quizzes (id, lesson_id, title, passing_score, questions_per_attempt, daily_attempt_limit)
VALUES
    (1, 1, 'Introduction to Databases', 60.00, 3, 3),
    (2, 2, 'Entity-Relationship Modeling', 60.00, 3, 3),
    (3, 5, 'SELECT and Joins', 60.00, 3, 3)
ON CONFLICT (lesson_id) DO NOTHING;

INSERT INTO public.quiz_questions (id, quiz_id, question_text, sequence_order)
VALUES
    (1,  1, 'What does a relational database store data in?', 1),
    (2,  1, 'Which of these is a relational database?', 2),
    (3,  1, 'What does SQL stand for?', 3),
    (4,  2, 'In an ER model, what does a rectangle represent?', 1),
    (5,  2, 'What is a primary key?', 2),
    (6,  2, 'A relationship between two entities is drawn as:', 3),
    (7,  3, 'Which SQL keyword filters rows?', 1),
    (8,  3, 'What type of JOIN returns only matching rows?', 2),
    (9,  3, 'Which clause orders the result set?', 3)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.quiz_options (question_id, option_label, option_text, is_correct)
VALUES
    (1, 'A', 'Tables of rows and columns', TRUE),
    (1, 'B', 'JSON documents only', FALSE),
    (1, 'C', 'Files and folders', FALSE),
    (1, 'D', 'Graph nodes', FALSE),
    (2, 'A', 'MongoDB', FALSE),
    (2, 'B', 'PostgreSQL', TRUE),
    (2, 'C', 'Redis', FALSE),
    (2, 'D', 'Neo4j', FALSE),
    (3, 'A', 'Structured Query Language', TRUE),
    (3, 'B', 'Simple Query Language', FALSE),
    (3, 'C', 'Standard Question List', FALSE),
    (3, 'D', 'System Query Logic', FALSE),
    (4, 'A', 'Entity', TRUE),
    (4, 'B', 'Attribute', FALSE),
    (4, 'C', 'Relationship', FALSE),
    (4, 'D', 'Constraint', FALSE),
    (5, 'A', 'A column that uniquely identifies a row', TRUE),
    (5, 'B', 'A column that may repeat', FALSE),
    (5, 'C', 'A foreign key to another table', FALSE),
    (5, 'D', 'An index on a non-unique column', FALSE),
    (6, 'A', 'A dashed line', FALSE),
    (6, 'B', 'A diamond', TRUE),
    (6, 'C', 'A double rectangle', FALSE),
    (6, 'D', 'An oval', FALSE),
    (7, 'A', 'SELECT', FALSE),
    (7, 'B', 'WHERE', TRUE),
    (7, 'C', 'GROUP BY', FALSE),
    (7, 'D', 'JOIN', FALSE),
    (8, 'A', 'LEFT JOIN', FALSE),
    (8, 'B', 'RIGHT JOIN', FALSE),
    (8, 'C', 'INNER JOIN', TRUE),
    (8, 'D', 'FULL OUTER JOIN', FALSE),
    (9, 'A', 'ORDER BY', TRUE),
    (9, 'B', 'FILTER BY', FALSE),
    (9, 'C', 'SORT BY', FALSE),
    (9, 'D', 'GROUP BY', FALSE)
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.quizzes', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.quizzes)
);

SELECT setval(
    pg_get_serial_sequence('public.quiz_questions', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.quiz_questions)
);

SELECT setval(
    pg_get_serial_sequence('public.quiz_options', 'id'),
    (SELECT COALESCE(MAX(id), 1) FROM public.quiz_options)
);
