-- =========================================================
-- V12: Certificates
--
-- All schema for the certificate feature in one file:
--   * the certificates table (one per completed course/track)
--   * sp_issue_certificate -- the write path (idempotent)
--   * the auto-issue trigger that issues a course certificate the
--     moment an enrollment reaches 'completed'
--   * fn_certificate_verify -- public code lookup for verification
--   * certificate indexes
-- =========================================================

-- =========================================================
-- 1. Certificates table
-- =========================================================

CREATE TABLE public.certificates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT NOT NULL,
    type       VARCHAR(20) NOT NULL,
    course_id  BIGINT,
    track_id   BIGINT,
    cert_code  VARCHAR(100) NOT NULL,
    issued_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_certificates
        PRIMARY KEY (id),

    CONSTRAINT uq_certificates_code
        UNIQUE (cert_code),

    CONSTRAINT uq_certificates_user_entity
        UNIQUE (user_id, COALESCE(course_id, 0), COALESCE(track_id, 0)),

    CONSTRAINT fk_certificates_user
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_certificates_course
        FOREIGN KEY (course_id)
        REFERENCES public.courses (id)
        ON DELETE SET NULL,

    CONSTRAINT fk_certificates_track
        FOREIGN KEY (track_id)
        REFERENCES public.tracks (id)
        ON DELETE SET NULL,

    CONSTRAINT chk_certificates_type
        CHECK (type IN ('course', 'track')),

    CONSTRAINT chk_certificates_entity
        CHECK (
            (type = 'course' AND course_id IS NOT NULL AND track_id IS NULL)
            OR
            (type = 'track' AND track_id IS NOT NULL AND course_id IS NULL)
        )
);


-- =========================================================
-- 2. Issue procedure (idempotent)
-- =========================================================

-- Issues a certificate for a completed course or track. Idempotent:
-- when a certificate already exists it is returned unchanged instead
-- of raising, which makes the auto-issue trigger (below) safe to fire
-- on every completion transition.
CREATE OR REPLACE FUNCTION public.sp_issue_certificate(
    p_student_id BIGINT,
    p_entity_type VARCHAR,
    p_entity_id   BIGINT
)
RETURNS TABLE (
    certificate_id BIGINT,
    user_id        BIGINT,
    type           VARCHAR,
    course_id      BIGINT,
    track_id       BIGINT,
    cert_code      VARCHAR,
    issued_at      TIMESTAMPTZ,
    already_issued BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_normalized_type VARCHAR(20);
    v_completed       BOOLEAN;
    v_code            VARCHAR(100);
BEGIN
    IF NOT public.fn_user_is_active_student(p_student_id) THEN
        RAISE EXCEPTION 'LTU01: Only active students can receive certificates.'
            USING ERRCODE = 'LTU01';
    END IF;

    v_normalized_type := LOWER(BTRIM(COALESCE(p_entity_type, '')));
    IF v_normalized_type NOT IN ('course', 'track') THEN
        RAISE EXCEPTION 'LTCE1: entity_type must be course or track.'
            USING ERRCODE = 'LTCE1';
    END IF;

    -- Existing certificate: return it unchanged (idempotent).
    IF v_normalized_type = 'course' THEN
        SELECT c.id, c.user_id, c.type, c.course_id, c.track_id, c.cert_code, c.issued_at
        INTO certificate_id, user_id, type, course_id, track_id, cert_code, issued_at
        FROM public.certificates c
        WHERE c.user_id = p_student_id
          AND c.type = 'course'
          AND c.course_id = p_entity_id;

        IF certificate_id IS NOT NULL THEN
            already_issued := TRUE;
            RETURN NEXT;
            RETURN;
        END IF;

        SELECT EXISTS (
            SELECT 1
            FROM public.enrollments
            WHERE user_id = p_student_id
              AND course_id = p_entity_id
              AND status = 'completed'
        )
        INTO v_completed;

        IF NOT v_completed THEN
            RAISE EXCEPTION 'LTCE2: Course % is not completed by the student.', p_entity_id
                USING ERRCODE = 'LTCE2';
        END IF;
    ELSE
        SELECT c.id, c.user_id, c.type, c.course_id, c.track_id, c.cert_code, c.issued_at
        INTO certificate_id, user_id, type, course_id, track_id, cert_code, issued_at
        FROM public.certificates c
        WHERE c.user_id = p_student_id
          AND c.type = 'track'
          AND c.track_id = p_entity_id;

        IF certificate_id IS NOT NULL THEN
            already_issued := TRUE;
            RETURN NEXT;
            RETURN;
        END IF;

        SELECT EXISTS (
            SELECT 1
            FROM public.track_enrollments
            WHERE user_id = p_student_id
              AND track_id = p_entity_id
              AND status = 'completed'
        )
        INTO v_completed;

        IF NOT v_completed THEN
            RAISE EXCEPTION 'LTCE2: Track % is not completed by the student.', p_entity_id
                USING ERRCODE = 'LTCE2';
        END IF;
    END IF;

    v_code := 'LT-'
              || UPPER(
                  SUBSTRING(
                      MD5(
                          p_student_id::TEXT
                          || ':' || p_entity_type::TEXT
                          || ':' || p_entity_id::TEXT
                          || ':' || CURRENT_TIMESTAMP::TEXT
                      )
                      FOR 14
                  )
              );

    IF v_normalized_type = 'course' THEN
        INSERT INTO public.certificates (user_id, type, course_id, cert_code)
        VALUES (p_student_id, 'course', p_entity_id, v_code)
        RETURNING
            public.certificates.id,
            public.certificates.user_id,
            public.certificates.type,
            public.certificates.course_id,
            public.certificates.track_id,
            public.certificates.cert_code,
            public.certificates.issued_at
        INTO certificate_id, user_id, type, course_id, track_id, cert_code, issued_at;
    ELSE
        INSERT INTO public.certificates (user_id, type, track_id, cert_code)
        VALUES (p_student_id, 'track', p_entity_id, v_code)
        RETURNING
            public.certificates.id,
            public.certificates.user_id,
            public.certificates.type,
            public.certificates.course_id,
            public.certificates.track_id,
            public.certificates.cert_code,
            public.certificates.issued_at
        INTO certificate_id, user_id, type, course_id, track_id, cert_code, issued_at;
    END IF;

    already_issued := FALSE;
    RETURN NEXT;
    RETURN;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLSTATE IN ('LTU01', 'LTCE1', 'LTCE2', '23505') THEN
            RAISE;
        END IF;
        RAISE LOG 'sp_issue_certificate unexpected sqlstate=%: %', SQLSTATE, SQLERRM;
        RAISE EXCEPTION 'LT500: Unexpected database error while issuing the certificate: %', SQLERRM
            USING ERRCODE = 'LT500';
END;
$$;


-- =========================================================
-- 3. Auto-issue trigger on course completion
-- =========================================================

-- When an enrollment transitions to 'completed', issue the course
-- certificate automatically. sp_issue_certificate is idempotent, so
-- repeated/overlapping completion transitions are no-ops.
CREATE OR REPLACE FUNCTION public.fn_auto_issue_certificate_on_completion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM public.sp_issue_certificate(NEW.user_id, 'course', NEW.course_id);

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_auto_issue_certificate ON public.enrollments;
CREATE TRIGGER trg_auto_issue_certificate
AFTER UPDATE OF status ON public.enrollments
FOR EACH ROW
WHEN (NEW.status = 'completed' AND OLD.status IS DISTINCT FROM 'completed')
EXECUTE FUNCTION public.fn_auto_issue_certificate_on_completion();


-- =========================================================
-- 4. Verification lookup
-- =========================================================

-- Public lookup by certificate code; used by the verify page.
CREATE OR REPLACE FUNCTION public.fn_certificate_verify(p_cert_code VARCHAR)
RETURNS TABLE (
    certificate_id BIGINT,
    cert_code      VARCHAR,
    type           VARCHAR,
    holder_name    TEXT,
    entity_title   TEXT,
    issued_at      TIMESTAMPTZ
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        c.id,
        c.cert_code,
        c.type,
        CONCAT_WS(' ', u.first_name, u.last_name),
        CASE
            WHEN c.type = 'course'
                THEN co.title
            WHEN c.type = 'track'
                THEN t.title
        END,
        c.issued_at
    FROM public.certificates c
    JOIN public.users u ON u.id = c.user_id
    LEFT JOIN public.courses co ON co.id = c.course_id
    LEFT JOIN public.tracks t ON t.id = c.track_id
    WHERE c.cert_code = BTRIM(p_cert_code);
$$;


-- =========================================================
-- 5. Certificate indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_certificates_user_issued
    ON public.certificates (user_id, issued_at DESC);
